package com.example.utils.xml.exceptions;

import lombok.experimental.StandardException;

/**
 * A custom runtime exception for all errors generated by the XML utility library. This wraps underlying exceptions (e.g., SAXException,
 * IOException) to provide a consistent exception type for library users.
 *
 * @author Gemini
 */
@StandardException
public class XmlException extends RuntimeException {}
